import jsPDF from "jspdf";

const MARGIN = 14;
const PAGE_W = 210;
const PAGE_H = 297;
const PRIMARY = "#3b82f6";
const DARK = "#0f172a";

export interface CompareExportEntry {
  major: string;
  skills: string[];
  careers: string[];
  countries: { name: string; flag: string }[];
  studyCostLabel: string;
  pathways: { label: string; roles: string[] }[];
}

export function generateComparePDF(entries: CompareExportEntry[]): void {
  const doc = new jsPDF({ orientation: "landscape", unit: "mm", format: "a4" });
  // A4 landscape: 297mm × 210mm
  const pageW = PAGE_H; // 297 in landscape
  const pageH = PAGE_W; // 210 in landscape

  // Header bar
  doc.setFillColor(PRIMARY);
  doc.rect(0, 0, pageW, 14, "F");
  doc.setTextColor("#ffffff");
  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  doc.text("NORTHVOY — Major Comparison", MARGIN, 9);
  doc.text(new Date().toLocaleDateString(), pageW - MARGIN, 9, { align: "right" });

  // Column layout
  const colCount = entries.length;
  const colW = (pageW - MARGIN * 2 - (colCount - 1) * 6) / colCount;

  let y = 20;

  // Column headers
  entries.forEach((entry, i) => {
    const x = MARGIN + i * (colW + 6);
    doc.setFillColor(DARK);
    doc.roundedRect(x, y, colW, 10, 2, 2, "F");
    doc.setTextColor("#ffffff");
    doc.setFontSize(8);
    doc.setFont("helvetica", "bold");
    const lines = doc.splitTextToSize(entry.major, colW - 4);
    doc.text(lines[0], x + 2, y + 6.5);
  });

  y += 14;

  // Sections to render
  const sections: { label: string; getValue: (e: CompareExportEntry) => string[] }[] = [
    { label: "Key Skills", getValue: e => e.skills },
    { label: "Careers", getValue: e => e.careers },
    { label: "Top Countries", getValue: e => e.countries.map(c => `${c.flag} ${c.name}`) },
    { label: "Study Cost", getValue: e => [e.studyCostLabel] },
    { label: "Career Pathways", getValue: e => e.pathways.map(p => p.label) },
  ];

  sections.forEach(section => {
    // Section label row
    doc.setFillColor("#f1f5f9");
    doc.rect(MARGIN, y, pageW - MARGIN * 2, 7, "F");
    doc.setTextColor(DARK);
    doc.setFontSize(8);
    doc.setFont("helvetica", "bold");
    doc.text(section.label, MARGIN + 2, y + 5);
    y += 9;

    // Determine max rows needed
    const maxRows = Math.max(...entries.map(e => section.getValue(e).length));

    doc.setTextColor("#334155");
    doc.setFont("helvetica", "normal");
    doc.setFontSize(7.5);

    for (let row = 0; row < maxRows; row++) {
      entries.forEach((entry, i) => {
        const x = MARGIN + i * (colW + 6);
        const items = section.getValue(entry);
        const text = items[row] ?? "";
        const lines = doc.splitTextToSize(text, colW - 4);
        doc.text(lines, x + 2, y + 4);
      });
      y += 6;
    }

    y += 4;

    // New page if needed
    if (y > pageH - 20) {
      doc.addPage();
      y = 14;
    }
  });

  // Footer
  doc.setFontSize(7);
  doc.setTextColor("#94a3b8");
  doc.text("Generated by NorthVoy · northvoy.com · For guidance purposes only", pageW / 2, pageH - 6, { align: "center" });

  doc.save("NorthVoy_MajorComparison.pdf");
}
