export interface Scholarship {
  id: string;
  name: string;
  provider: string;
  countries: string[];        // destination countries
  majors: string[];           // relevant fields (empty = all fields)
  amount: string;
  coverage: string;           // what it covers
  eligibility: string;
  deadline: string;           // "Varies" | "January" | specific
  link: string;
  type: "full" | "partial" | "living" | "merit" | "need-based";
  citizenships: string[];     // who can apply (empty = all nationalities)
  tags: string[];
}

export const SCHOLARSHIPS: Scholarship[] = [
  // ── EUROPE ────────────────────────────────────────────────────────────────
  {
    id: "erasmus-mundus",
    name: "Erasmus Mundus Joint Master",
    provider: "European Commission",
    countries: ["Germany", "France", "Netherlands", "Sweden", "Belgium", "Spain", "Italy", "Austria"],
    majors: [],
    amount: "Up to €1,400/month + tuition waiver",
    coverage: "Full tuition + monthly stipend + travel allowance",
    eligibility: "Bachelor's degree holders, any nationality",
    deadline: "January – March (varies by programme)",
    link: "https://erasmus-plus.ec.europa.eu/opportunities/individuals/students/erasmus-mundus-joint-masters",
    type: "full",
    citizenships: [],
    tags: ["EU", "Masters", "All fields", "Fully funded"],
  },
  {
    id: "daad-germany",
    name: "DAAD Scholarship",
    provider: "German Academic Exchange Service",
    countries: ["Germany"],
    majors: [],
    amount: "€861–€1,200/month + benefits",
    coverage: "Monthly stipend, health insurance, travel allowance",
    eligibility: "Bachelor's graduates, excellent academic record",
    deadline: "October – November (for the following year)",
    link: "https://www.daad.de/en/study-and-research-in-germany/scholarships/",
    type: "merit",
    citizenships: [],
    tags: ["Germany", "Masters", "PhD", "All fields"],
  },
  {
    id: "chevening",
    name: "Chevening Scholarship",
    provider: "UK Government (FCDO)",
    countries: ["United Kingdom"],
    majors: [],
    amount: "Full funding",
    coverage: "Full tuition, living allowance, flights, visa",
    eligibility: "2+ years work experience, leadership potential, any field",
    deadline: "November each year",
    link: "https://www.chevening.org/scholarships/",
    type: "full",
    citizenships: [],
    tags: ["UK", "Masters", "Leadership", "Fully funded"],
  },
  {
    id: "commonwealth-masters",
    name: "Commonwealth Masters Scholarship",
    provider: "Commonwealth Scholarship Commission",
    countries: ["United Kingdom"],
    majors: [],
    amount: "Full funding",
    coverage: "Tuition, living allowance, airfare, thesis grant",
    eligibility: "Citizens of Commonwealth countries, first class degree",
    deadline: "December each year",
    link: "https://cscuk.fcdo.gov.uk/scholarships/commonwealth-masters-scholarships/",
    type: "full",
    citizenships: ["Commonwealth countries"],
    tags: ["UK", "Masters", "Commonwealth", "Fully funded"],
  },
  {
    id: "sverige-sweden",
    name: "Swedish Institute Scholarships (SISGP)",
    provider: "Swedish Institute",
    countries: ["Sweden"],
    majors: [],
    amount: "SEK 11,000/month + tuition",
    coverage: "Full tuition + living costs + insurance + travel",
    eligibility: "Bachelor's degree, 3,000 hours work experience, leadership",
    deadline: "February each year",
    link: "https://si.se/en/apply/scholarships/swedish-institute-scholarships-for-global-professionals/",
    type: "full",
    citizenships: [],
    tags: ["Sweden", "Masters", "Leadership", "Fully funded"],
  },
  {
    id: "holland-scholarship",
    name: "Holland Scholarship",
    provider: "Dutch Ministry of Education",
    countries: ["Netherlands"],
    majors: [],
    amount: "€5,000 (one-time)",
    coverage: "Partial living costs",
    eligibility: "Non-EEA students, Bachelor's or Master's",
    deadline: "February – May (varies by university)",
    link: "https://www.studyinholland.nl/finances/scholarships/holland-scholarship",
    type: "partial",
    citizenships: [],
    tags: ["Netherlands", "Non-EU", "Bachelor", "Masters"],
  },
  {
    id: "swiss-excellence",
    name: "Swiss Government Excellence Scholarships",
    provider: "Swiss Confederation",
    countries: ["Switzerland"],
    majors: [],
    amount: "CHF 1,920/month + tuition waiver",
    coverage: "Monthly stipend, tuition, accommodation supplement",
    eligibility: "Master's/PhD candidates, under 35 (postdoc under 40)",
    deadline: "November – February (varies by country)",
    link: "https://www.sbfi.admin.ch/sbfi/en/home/education/scholarships-and-grants/swiss-government-excellence-scholarships.html",
    type: "full",
    citizenships: [],
    tags: ["Switzerland", "Masters", "PhD", "Research"],
  },
  {
    id: "gates-cambridge",
    name: "Gates Cambridge Scholarship",
    provider: "Bill & Melinda Gates Foundation",
    countries: ["United Kingdom"],
    majors: [],
    amount: "Full funding",
    coverage: "Full tuition + maintenance allowance + flights",
    eligibility: "Outstanding academics, leadership, social commitment, non-UK",
    deadline: "October – December (varies by course)",
    link: "https://www.gatescambridge.org/",
    type: "full",
    citizenships: [],
    tags: ["Cambridge", "Masters", "PhD", "Fully funded", "Prestigious"],
  },
  {
    id: "rhodes-oxford",
    name: "Rhodes Scholarship",
    provider: "Rhodes Trust",
    countries: ["United Kingdom"],
    majors: [],
    amount: "Full funding",
    coverage: "Full tuition + living stipend + airfare",
    eligibility: "Exceptional academic record, leadership, character",
    deadline: "August – October (varies by country)",
    link: "https://www.rhodeshouse.ox.ac.uk/scholarships/",
    type: "full",
    citizenships: [],
    tags: ["Oxford", "Masters", "PhD", "Prestigious", "Fully funded"],
  },

  // ── NORTH AMERICA ─────────────────────────────────────────────────────────
  {
    id: "fulbright",
    name: "Fulbright Foreign Student Program",
    provider: "U.S. Department of State",
    countries: ["United States"],
    majors: [],
    amount: "Full funding",
    coverage: "Tuition, living allowance, health insurance, airfare",
    eligibility: "Non-US citizens, Bachelor's degree, varies by home country",
    deadline: "Varies by country (typically Feb–Oct)",
    link: "https://foreign.fulbrightonline.org/",
    type: "full",
    citizenships: [],
    tags: ["USA", "Masters", "PhD", "Fully funded", "Research"],
  },
  {
    id: "vanier-canada",
    name: "Vanier Canada Graduate Scholarship",
    provider: "Government of Canada",
    countries: ["Canada"],
    majors: [],
    amount: "CA$50,000/year (3 years)",
    coverage: "Living stipend for doctoral studies",
    eligibility: "PhD students, academic excellence, leadership",
    deadline: "November each year",
    link: "https://vanier.gc.ca/",
    type: "merit",
    citizenships: [],
    tags: ["Canada", "PhD", "Research", "Leadership"],
  },
  {
    id: "canada-scholarships",
    name: "Canada-ASEAN Scholarships",
    provider: "Global Affairs Canada",
    countries: ["Canada"],
    majors: [],
    amount: "CA$10,200 + travel",
    coverage: "Living costs + return airfare + health insurance",
    eligibility: "ASEAN country citizens, short-term study/research",
    deadline: "February each year",
    link: "https://www.educanada.ca/scholarships-bourses/can/institutions/asean-anase.aspx",
    type: "full",
    citizenships: ["ASEAN countries"],
    tags: ["Canada", "Short-term", "ASEAN"],
  },

  // ── AUSTRALIA ─────────────────────────────────────────────────────────────
  {
    id: "australia-awards",
    name: "Australia Awards Scholarships",
    provider: "Australian Government (DFAT)",
    countries: ["Australia"],
    majors: [],
    amount: "Full funding",
    coverage: "Full tuition, living allowance, airfare, health cover",
    eligibility: "Citizens of eligible countries (Asia-Pacific, Africa, Middle East)",
    deadline: "April – June (varies by country)",
    link: "https://www.australiaawards.gov.au/",
    type: "full",
    citizenships: [],
    tags: ["Australia", "Masters", "PhD", "Fully funded", "Development"],
  },
  {
    id: "rtp-australia",
    name: "Research Training Program (RTP)",
    provider: "Australian Government",
    countries: ["Australia"],
    majors: [],
    amount: "AU$32,500/year + tuition waiver",
    coverage: "Tuition fee offset + living stipend",
    eligibility: "Domestic & international research degree applicants",
    deadline: "Varies by university (Oct–Nov typical)",
    link: "https://www.dese.gov.au/research-training-program",
    type: "full",
    citizenships: [],
    tags: ["Australia", "PhD", "Research", "Masters by Research"],
  },

  // ── ASIA ──────────────────────────────────────────────────────────────────
  {
    id: "singapore-asean",
    name: "ASEAN Undergraduate Scholarship (NUS/NTU)",
    provider: "NUS / NTU Singapore",
    countries: ["Singapore"],
    majors: [],
    amount: "Full tuition + S$5,800/year allowance",
    coverage: "Tuition, accommodation, return airfare, living allowance",
    eligibility: "ASEAN citizens, excellent grades, under 25",
    deadline: "February – March each year",
    link: "https://nus.edu.sg/oam/scholarships/asean-scholarship.html",
    type: "full",
    citizenships: ["ASEAN countries"],
    tags: ["Singapore", "Bachelor", "ASEAN", "Fully funded"],
  },
  {
    id: "mext-japan",
    name: "MEXT Japanese Government Scholarship",
    provider: "Japanese Ministry of Education",
    countries: ["Japan"],
    majors: [],
    amount: "¥117,000–¥145,000/month + tuition waiver",
    coverage: "Full tuition + monthly stipend + airfare",
    eligibility: "Under 35 for most programmes, Bachelor's degree",
    deadline: "May – June (varies by embassy)",
    link: "https://www.mext.go.jp/en/policy/education/highered/title02/detail02/sdetail02/1373897.htm",
    type: "full",
    citizenships: [],
    tags: ["Japan", "Masters", "PhD", "Fully funded"],
  },

  // ── FIELD-SPECIFIC ────────────────────────────────────────────────────────
  {
    id: "wellcome-trust",
    name: "Wellcome Trust Fellowships",
    provider: "Wellcome Trust",
    countries: ["United Kingdom", "United States", "Australia"],
    majors: ["Medicine", "Biomedical Science", "Public Health", "Biology"],
    amount: "Full funding (varies by scheme)",
    coverage: "Salary, research costs, training budget",
    eligibility: "Researchers in biomedical & health sciences",
    deadline: "Multiple rounds per year",
    link: "https://wellcome.org/grant-funding",
    type: "merit",
    citizenships: [],
    tags: ["Medicine", "Research", "PhD", "Postdoc", "Health Sciences"],
  },
  {
    id: "google-lime",
    name: "Google Lime Scholarship",
    provider: "Google / Lime Connect",
    countries: ["United States", "Canada"],
    majors: ["Computer Science", "Software Engineering", "Data Science"],
    amount: "US$10,000",
    coverage: "One-year scholarship + Google internship opportunity",
    eligibility: "Students with disabilities studying CS-related fields",
    deadline: "December each year",
    link: "https://buildyourfuture.withgoogle.com/scholarships/google-lime-scholarship",
    type: "partial",
    citizenships: [],
    tags: ["CS", "Tech", "Disability", "USA", "Canada"],
  },
  {
    id: "aauw-tech",
    name: "AAUW International Fellowships",
    provider: "AAUW",
    countries: ["United States"],
    majors: [],
    amount: "US$18,000–$30,000/year",
    coverage: "Living expenses for full-time study",
    eligibility: "Women who are not US citizens, full-time Masters/PhD",
    deadline: "November each year",
    link: "https://www.aauw.org/resources/programs/fellowships-grants/current-opportunities/international/",
    type: "merit",
    citizenships: [],
    tags: ["USA", "Women", "Masters", "PhD", "All fields"],
  },
  {
    id: "agrikola-finland",
    name: "Finland Government Scholarship Pool",
    provider: "CIMO / Finnish National Agency for Education",
    countries: ["Finland"],
    majors: [],
    amount: "€1,500/month",
    coverage: "Monthly grant for research stays",
    eligibility: "Doctoral/postdoctoral researchers from partner countries",
    deadline: "January – February each year",
    link: "https://www.oph.fi/en/programmes-and-grants/scholarships-and-grants",
    type: "partial",
    citizenships: [],
    tags: ["Finland", "PhD", "Research", "Postdoc"],
  },
];

// ── Helpers ───────────────────────────────────────────────────────────────────

export function getScholarshipsForProfile(
  countries: string[],
  majors: string[],
): Scholarship[] {
  return SCHOLARSHIPS.filter(s => {
    const countryMatch = countries.length === 0 || s.countries.some(c => countries.includes(c));
    const majorMatch = s.majors.length === 0 || majors.length === 0 ||
      s.majors.some(m => majors.some(userMajor =>
        userMajor.toLowerCase().includes(m.toLowerCase()) ||
        m.toLowerCase().includes(userMajor.toLowerCase().split(" ")[0])
      ));
    return countryMatch && majorMatch;
  });
}

export const ALL_SCHOLARSHIP_COUNTRIES = [
  ...new Set(SCHOLARSHIPS.flatMap(s => s.countries))
].sort();

export const TYPE_LABELS: Record<Scholarship["type"], string> = {
  "full":       "Fully Funded",
  "partial":    "Partial",
  "living":     "Living Grant",
  "merit":      "Merit-based",
  "need-based": "Need-based",
};
